### ISSUE TITLE
cant switch back to current week 

### ISSUE THREAD

**Issue by Tallerik** [Jeidnx/untismerger#31]
There is no issue with navigation through the weeks, but when you want back to the current week, nothing happens and this error apear:
![grafik](https://user-images.githubusercontent.com/18576088/141430659-0922a0ae-515a-4543-9cf6-5f4d0d3df41b.png)

Reproduce:
1. Go on https://untismerger.tk [Assuming logged in]
2. Navigate with [D] through multiple weeks
3. Use [A] to go back. It will work, but the last page (current work) wont be accessible again.

Workaround:
F5

**Comment by Jeidnx** [comment]
The current live version of the timetable.js File has exactly 321 lines.
Im Pretty sure the error message has nothing to do with the Problem.
The Problem only appears on Friday trough Sunday afaik

**Comment by Tallerik** [comment]
Im not sure if the error is related to this issue.
It occured on an friday
