### ISSUE TITLE
Multiple Lessons at same time

### ISSUE THREAD

**Issue by Tallerik** [Jeidnx/untismerger#34]
In Untis there is the ability to have multiple Lessons at the same time. Untismerger only shows one. This should be changed because when a Lesson is replaced with another it shows in untis that the normal Lesson is canceled but also shows the new Lesson. In this case Untismerger only shows the canceled lesson which implements that there is no Lesson.

**Comment by Jeidnx** [comment]
The word you are lookinf or is not implements but implies.
This should have been fixed in #22 but i will look into this again

**Comment by Jeidnx** [comment]
Should be fixed.
